import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin:
https://github.com/JamieSharpe/obsidian-wordpress-reloaded
https://github.com/bugparty/obsidian-wordpress-reloaded
https://github.com/devbean/obsidian-wordpress
*/
`;

const mode = process.argv[2]; // "production" | "debug" | undefined (dev/watch)
const prod = mode === "production";
const debug = mode === "debug";

const nodeEnv = prod ? '"production"' : debug ? '"debug"' : '"development"';

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	minify: prod,
	define: {
		"process.env.NODE_ENV": nodeEnv
	},
	outfile: "main.js",
});

if (prod || debug) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}